[settings]
idiomatic_version_file_enable_tools = ["node", "npm"]

[env]
_.file = "{{config_root}}/.env"
_.path = ['{{config_root}}/node_modules/.bin']
NODE_PACKAGE_MANAGER="npm"

[tools]
prek = "latest"

[hooks]
enter = ["mise run setup"]

[tasks.setup]
description = "Initialize the repository"
depends = ["install-packages", "install-hooks"]

[tasks.install-packages]
description = "Install node dependencies when package.json changed"
alias = "ip"
silent = "stdout"
sources = ["package.json"]
outputs = ["node_modules/.package.json"]
run = '''
if [ -f package.json ] && [ -z "${NODE_NO_INSTALL_PACKAGES:-}" ]; then
  if [ ! -d node_modules ] || [ ! -f node_modules/.package.json ] || [ node_modules/.package.json -ot package.json ]; then
    if [ -z "${NODE_PACKAGE_MANAGER:-}" ]; then
      if [ -f yarn.lock ]; then
        echo "Installing dependencies using yarn..."
        yarn install
      elif [ -f package-lock.json ]; then
        echo "Installing dependencies using npm..."
        npm install
      else
        echo "No supported lock file found. Installing dependencies using yarn..."
        yarn install
      fi
    else
      echo "Installing dependencies with ${NODE_PACKAGE_MANAGER}..."
      ${NODE_PACKAGE_MANAGER} install
    fi
    mkdir -p node_modules
    touch node_modules/.package.json
  fi
fi
'''

[tasks.install-hooks]
description = "Setup git hooks using prek"
alias = "ih"
sources = [".pre-commit-config.yaml"]
outputs = [".git/prek-hooks-configured"]
silent = "stdout"
run = '''
if test -f .pre-commit-config.yaml && test -d .git; then
  prek install --overwrite && touch .git/prek-hooks-configured
fi
'''

[[watch_files]]
patterns = ["package.json"]
run = "mise run install-packages"
